# Generated by Django 4.2.3 on 2023-07-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserFunctional', '0002_alter_user_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Huly',
        ),
    ]
