# Generated by Django 4.2.3 on 2023-07-28 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserFunctional', '0003_rename_user_user_huly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='UserFunctional.user_huly'),
        ),
    ]
