# Generated by Django 4.2.3 on 2023-07-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('item_brand', models.CharField(max_length=20)),
                ('item_cur_price', models.CharField(max_length=20)),
                ('item_prev_price', models.CharField(max_length=20)),
                ('item_link', models.URLField(max_length=300, null=True)),
                ('item_date', models.TimeField(auto_now=True)),
                ('item_image', models.URLField(max_length=300, null=True)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='mainPage.categories')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
