# Generated by Django 4.2.3 on 2023-07-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='item_slug',
            new_name='slug',
        ),
    ]
